[package]
name = "raiden"
version = "0.1.0"
authors = ["bokuweb <bokuweb12@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
again = "0.1"
base64 = "^0.21"
raiden-derive = { version = "*", path = "../raiden-derive" }
rusoto_core_default = { package = "rusoto_core", version = "0.48", optional = true }
rusoto_core_rustls = { package = "rusoto_core", version = "0.48", default_features = false, features = [
    "rustls",
], optional = true }
rusoto_credential = "0.48"
rusoto_dynamodb_default = { package = "rusoto_dynamodb", version = "0.48", features = [
    "serialize_structs",
], optional = true }
rusoto_dynamodb_rustls = { package = "rusoto_dynamodb", version = "0.48", default_features = false, features = [
    "rustls",
    "serialize_structs",
], optional = true }
rust-crypto = "^0.2.36"
safe-builder = { tag = "0.0.6", git = "https://github.com/raiden-rs/safe-builder.git" }
serde = { version = "^1", features = ["derive"] }
serde_derive = "^1"
serde_json = "^1"
thiserror = "^1"
uuid = { version = "^1.4.1", features = ["v4"] }

[dev-dependencies]
pretty_assertions = "1.3.0"
pretty_env_logger = "0.5"
tokio = "1.33.0"

[features]
default = ["rusoto_core_default", "rusoto_dynamodb_default"]
rustls = ["rusoto_core_rustls", "rusoto_dynamodb_rustls"]
