[package]
name = "raiden-derive"
version = "0.1.0"
authors = ["bokuweb <bokuweb12@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "^1.0"
proc-quote = "0.4.0"
syn = "^1.0"
proc-macro2 = "^1.0.56"
ident_case = "^1.0.1"
convert_case = "^0.4.0"
safe-builder = { tag = "0.0.6", git = "https://github.com/raiden-rs/safe-builder.git" }

