[package]
name = "raiden-derive"
version = "0.1.0"
authors = ["bokuweb <bokuweb12@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "^1.0"
proc-quote = "0.3.2"
syn = "^1.0"
proc-macro2 = "^1.0"
ident_case = "^1.0"
derive_builder = "^0.9"
